# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
pr: &pr {type: select, proxies: [🚀 节点选择, 🛩️🌏 高速节点, 🔯 故障转移, 🛩️🇨🇳🇭🇰 高速香港节点, 🔯🇨🇳🇭🇰 故转香港节点, 🇨🇳🇭🇰 香港节点, 🛩️🇨🇳🇹🇼 高速台湾节点, 🔯🇨🇳🇹🇼 故转台湾节点, 🇨🇳🇹🇼 台湾节点, 🛩️🇯🇵 高速日本节点, 🔯🇯🇵 故转日本节点, 🇯🇵 日本节点, 🛩️🇸🇬 高速狮城节点, 🇸🇬 狮城节点, 🛩️🇰🇷 高速韩国节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🛩️🇺🇲 高速美国节点, 🛩️🌏 高速其他节点, 🌏 其他节点, 🌏 奇怪的特殊接入, 🚀 手动切换, 直连]}
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [🛩️🌏 高速节点, 🔯 故障转移, 🛩️🇨🇳🇭🇰 高速香港节点, 🔯🇨🇳🇭🇰 故转香港节点, 🇨🇳🇭🇰 香港节点, 🛩️🇨🇳🇹🇼 高速台湾节点, 🔯🇨🇳🇹🇼 故转台湾节点, 🇨🇳🇹🇼 台湾节点, 🛩️🇯🇵 高速日本节点, 🔯🇯🇵 故转日本节点, 🇯🇵 日本节点, 🛩️🇸🇬 高速狮城节点, 🇸🇬 狮城节点, 🛩️🇰🇷 高速韩国节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🛩️🇺🇲 高速美国节点, 🛩️🌏 高速其他节点, 🌏 其他节点, 🌏 奇怪的特殊接入, 🚀 手动切换, 直连]}
  - {name: 🇨🇳🇭🇰 香港节点, type: select, include-all: true, filter: "(?i)HK|HongKong|Hong Kong|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港|港"}
  - {name: 🇨🇳🇹🇼 台湾节点, type: select, include-all: true, filter: "(?i)TW|Taiwan|台湾|台北|台中|新北|彰化|嘉义|桃园|CHT|新北|台|HINET"}
  - {name: 🇯🇵 日本节点, type: select, include-all: true, filter: "(?i)JP|Japan|日本|东京|大阪|埼玉|沪日|穗日|川日|中日|泉日|杭日"}
  - {name: 🇸🇬 狮城节点, type: select, include-all: true, filter: "(?i)SG|Singapore|新加坡|狮城|沪新|京新|泉新|穗新|深新|杭新"}
  - {name: 🇰🇷 韩国节点, type: select, include-all: true, filter: "(?i)KR|Korea|KOR|韩国|首尔|韩|韓"}
  - {name: 🇺🇲 美国节点, type: select, include-all: true, filter: "(?i)US|America|UnitedStates|United States|美国|美|京美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美"}
  - {name: 🌏 其他节点, type: select, include-all: true, filter: "(?i)AC|AR|阿根廷|奥地利|维也纳|AU|Australia|Sydney|澳大利亚|悉尼|BE|BR|Brazil|巴西|圣保罗|Canada|加拿大|蒙特利尔|温哥华|楓葉|枫叶|🇨🇦|瑞士|苏黎世|DE|Germany|德国|法兰克福|德|丹麦|ES|EU|Finland|芬兰|赫尔辛基|FR|France|法国|巴黎|UK|England|UnitedKingdom|英国|英|伦敦|Indonesia|印尼|印度尼西亚|雅加达|Ireland|爱尔兰|都柏林|India|印度|孟买|Italy|意大利|米兰|KP|朝鲜|MO|Macao|澳门|CTM|MY|Malaysia|马来西亚|NL|Netherlands|荷兰|阿姆斯特丹|PH|Philippines|菲律宾|RO|罗马尼亚|RU|Russia|俄罗斯|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|京俄|杭俄|沙特|迪拜|SE|Sweden|TH|Thailand|泰国|曼谷|TR|Turkey|土耳其|伊斯坦布尔|VN|越南|ZA|南非|PL|波兰|NG|尼日利亚"}
  - {name: 🌏 奇怪的特殊接入, type: select, include-all: true, filter: "(?i)IPV6|官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|套餐"}
  - {name: 🚀 手动切换, type: select, include-all: true, filter: "(?=.*)^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量)).)*$"}
  - {name: 🐍 EX绅士, <<: *pr}
  #- {name: 🐲 Cygames, <<: *pr}
  - {name: 🎮 游戏平台, <<: *pr}
  #- {name: 📺 巴哈姆特, type: select, include-all: true, filter: "(?i)巴哈|动画疯|動畫瘋"}
  - {name: 📺 哔哩哔哩, type: select, proxies: [ 直连, 🇨🇳🇭🇰 香港节点, 🇨🇳🇹🇼 台湾节点]}
  - {name: 📹 YouTube, <<: *pr}
  - {name: 🍀 Google, <<: *pr}
  - {name: 👨🏿‍💻 GitHub, <<: *pr}
  - {name: 🐬 OneDrive, <<: *pr}
  - {name: 🪟 Microsoft, <<: *pr}
  - {name: 📲 Telegram, <<: *pr}
  #- {name: 🎥 NETFLIX, type: select, include-all: true, filter: "(?i)NF|奈飞|Netflix|NETFLIX"}
  #- {name: ✈️ Speedtest, <<: *pr}
  #- {name: 💶 PayPal, <<: *pr}
  - {name: 🍎 Apple, type: select, proxies: [直连, 🚀 节点选择]}
  - {name: 🎯 直连, type: select, proxies: [直连, 🚀 节点选择]}
  - {name: 🛑 广告, type: select, proxies: [直连, REJECT]}
  - {name: 🐟 漏网之鱼, type: select, proxies: [🚀 节点选择,  直连]}
  - {name: 🔯 故障转移, type: fallback, interval: 600, proxies: [🔯🇨🇳🇭🇰 故转香港节点, 🔯🇨🇳🇹🇼 故转台湾节点, 🔯🇯🇵 故转日本节点, 🛩️🇸🇬 高速狮城节点, 🛩️🇰🇷 高速韩国节点, 🛩️🇺🇲 高速美国节点, 🛩️🌏 高速其他节点, 直连]}
  - {name: 🛩️🌏 高速节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(HK|HongKong|Hong Kong|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港|港|TW|Taiwan|台湾|台北|台中|新北|彰化|嘉义|桃园|CHT|新北|台|HINET|JP|Japan|日本|东京|大阪|埼玉|沪日|穗日|川日|中日|泉日|杭日|SG|Singapore|新加坡|狮城|沪新|京新|泉新|穗新|深新|杭新))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🛩️🇨🇳🇭🇰 高速香港节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(HK|HongKong|Hong Kong|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港|港))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🔯🇨🇳🇭🇰 故转香港节点, type: fallback, include-all: true, interval: 600, filter: "(?=.*(HK|HongKong|Hong Kong|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港|港))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🛩️🇨🇳🇹🇼 高速台湾节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(TW|Taiwan|台湾|台北|台中|新北|彰化|嘉义|桃园|CHT|新北|台|HINET))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🔯🇨🇳🇹🇼 故转台湾节点, type: fallback, include-all: true, interval: 600, filter: "(?=.*(TW|Taiwan|台湾|台北|台中|新北|彰化|嘉义|桃园|CHT|新北|台|HINET))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🛩️🇯🇵 高速日本节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(JP|Japan|日本|东京|大阪|埼玉|沪日|穗日|川日|中日|泉日|杭日))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🔯🇯🇵 故转日本节点, type: fallback, include-all: true, interval: 600, filter: "(?=.*(JP|Japan|日本|东京|大阪|埼玉|沪日|穗日|川日|中日|泉日|杭日))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🛩️🇸🇬 高速狮城节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(SG|Singapore|新加坡|狮城|沪新|京新|泉新|穗新|深新|杭新))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🛩️🇰🇷 高速韩国节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(KR|Korea|KOR|韩国|首尔|韩|韓))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🛩️🇺🇲 高速美国节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(US|America|UnitedStates|United States|美国|美|京美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}
  - {name: 🛩️🌏 高速其他节点, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "(?=.*(AC|AR|阿根廷|奥地利|维也纳|AU|Australia|Sydney|澳大利亚|悉尼|BE|BR|Brazil|巴西|圣保罗|Canada|加拿大|蒙特利尔|温哥华|楓葉|枫叶|🇨🇦|瑞士|苏黎世|DE|Germany|德国|法兰克福|德|丹麦|ES|EU|Finland|芬兰|赫尔辛基|FR|France|法国|巴黎|UK|England|UnitedKingdom|英国|英|伦敦|Indonesia|印尼|印度尼西亚|雅加达|Ireland|爱尔兰|都柏林|India|印度|孟买|Italy|意大利|米兰|KP|朝鲜|MO|Macao|澳门|CTM|MY|Malaysia|马来西亚|NL|Netherlands|荷兰|阿姆斯特丹|PH|Philippines|菲律宾|RO|罗马尼亚|RU|Russia|俄罗斯|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|京俄|杭俄|沙特|迪拜|SE|Sweden|TH|Thailand|泰国|曼谷|TR|Turkey|土耳其|伊斯坦布尔|VN|越南|ZA|南非|PL|波兰|NG|尼日利亚))^((?!(官网|回家|返利|本站|永久|免费|精简|懒人|垃圾|备用|客服|长期|专用|临时|直连|家宽|剩余|流量|UDP|0.5|0.5倍|x0.5|2.0|2倍|x2|3.0|3倍|x3|4.0|4倍|x4|5.0|5倍|x5)).)*$"}

# 规则匹配
# 此规则部分没有做防泄露处理，因为弊严重大于利！
rules:
  - DOMAIN-SUFFIX,github.com/xiaojunsp,🚀 节点选择
  - DOMAIN-SUFFIX,weather.com,🎯 直连
  - DOMAIN-SUFFIX,openweathermap.org,🎯 直连
  - DOMAIN-SUFFIX,weatherapi.com,🎯 直连
  - DOMAIN-SUFFIX,accuweather.com,🎯 直连
  - DOMAIN-SUFFIX,met.no,🎯 直连
  - DOMAIN-KEYWORD,weather,🎯 直连  
  - RULE-SET,Direct,🎯 直连
  - RULE-SET,private_domain,🎯 直连
  - RULE-SET,ad,🛑 广告 
  - RULE-SET,apple_domain,🍎 Apple
  - RULE-SET,Epic,🎮 游戏平台
  - RULE-SET,Origin,🎮 游戏平台
  - RULE-SET,Sony,🎮 游戏平台
  - RULE-SET,Steam,🎮 游戏平台
  - RULE-SET,Nintendo,🎮 游戏平台
  - RULE-SET,hk,🚀 节点选择
  - RULE-SET,ProxyLite,🚀 节点选择
  - RULE-SET,japan,🇯🇵 日本节点
  - RULE-SET,dmm,🇯🇵 日本节点
  - RULE-SET,exhentai,🐍 EX绅士
  #- RULE-SET,cygames,🐲 Cygames
  - RULE-SET,bilibili,📺 哔哩哔哩
  #- RULE-SET,bahamut,📺 巴哈姆特
  - RULE-SET,github_domain,👨🏿‍💻 GitHub
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,google_domain,🍀 Google
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🪟 Microsoft
  #- RULE-SET,speedtest_domain,✈️ Speedtest
  - RULE-SET,telegram_domain,📲 Telegram
  #- RULE-SET,netflix_domain,🎥 NETFLIX
  #- RULE-SET,paypal_domain,💶 PayPal
  - RULE-SET,cn_domain,🎯 直连
  - RULE-SET,Download,🎯 直连
  - RULE-SET,LocalAreaNetwork,🎯 直连
  - RULE-SET,UnBan,🎯 直连
  - RULE-SET,ChinaDomain,🎯 直连
  - RULE-SET,ChinaCompanyIp,🎯 直连
  - RULE-SET,cn_ip,🎯 直连,no-resolve
  - GEOIP,CN,🎯 直连
  - RULE-SET,google_ip,🍀 Google,no-resolve
  #- RULE-SET,netflix_ip,🎥 NETFLIX,no-resolve
  - RULE-SET,telegram_ip,📲 Telegram,no-resolve
  - RULE-SET,proxy,🚀 节点选择
  - RULE-SET,gfw_domain,🚀 节点选择
  - RULE-SET,geolocation-!cn,🚀 节点选择
  - MATCH,🐟 漏网之鱼

# 规则集
rule-anchor:
  ip: &ip {type: http, interval: 604800, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 604800, behavior: domain, format: mrs}
  class: &class {type: http, interval: 604800, behavior: classical, format: text}
rule-providers: 
  hk: { <<: *class, url: "https://raw.githubusercontent.com/xiaojunsp/clash/main/rules/hk.list"}
  japan: { <<: *class, url: "https://raw.githubusercontent.com/xiaojunsp/clash/main/rules/japan.list"}
  dmm: { <<: *class, url: "https://raw.githubusercontent.com/xiaojunsp/clash/main/rules/dmm.list"}
  exhentai: { <<: *class, url: "https://raw.githubusercontent.com/xiaojunsp/clash/main/rules/exhentai.list"}
  cygames: { <<: *class, url: "https://raw.githubusercontent.com/xiaojunsp/clash/main/rules/cygames.list"}
  Direct: { <<: *class, url: "https://raw.githubusercontent.com/xiaojunsp/clash/main/rules/Direct.list"}
  ProxyLite: { <<: *class, url: "https://raw.githubusercontent.com/xiaojunsp/clash/main/rules/ProxyLite.list"}
  Download: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"}
  LocalAreaNetwork: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"}
  UnBan: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"}
  ChinaDomain: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"}
  ChinaCompanyIp: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"}
  
  Epic: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/epicgames.mrs"}
  Origin: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/origin.mrs"}
  Sony: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/sony.mrs"}
  Steam: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"}
  Nintendo: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/nintendo.mrs"}
  bilibili: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs"}
  #bahamut: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/bahamut.mrs"}
  
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxy: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/proxy.mrs"}
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  #netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  #paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  #speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  #netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  
  ad: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/ad.mrs"}
